apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: null
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
