apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  template:
    spec:
      containers:
      - name: server
        startupProbe:
          tcpSocket:
            port: 7070
          failureThreshold: 30
          periodSeconds: 5
