apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: server
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: ENABLE_PROFILER
          value: "1"
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi 