apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: null
    spec:
      containers:
      - name: server
