apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: cartservice-cb
  namespace: dev
spec:
  host: cartservice.dev.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 5
