apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: frontend
  namespace: dev
spec:
  hosts:
  - frontend
  http:
  - retries:
      attempts: 2
      perTryTimeout: 1s
      retryOn: 5xx,connect-failure,refused-stream
    timeout: 3s
    route:
    - destination:
        host: frontend
