apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: frontend
  namespace: dev
spec:
  hosts:
  - "*"
  gateways:
  - boutique-gateway   # ✅ MUST match Gateway name + namespace
  http:
  - route:
    - destination:
        host: frontend.dev.svc.cluster.local
        port:
          number: 80
