apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-canary
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v2
  template:
    metadata:
      labels:
        app: frontend
        version: v2
    spec:
      containers:
      - name: server
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend:v0.10.3
        env:
        - name: ENABLE_PROFILER
          value: "1"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
