apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend-resilience
  namespace: dev
spec:
  hosts:
  - frontend
  gateways:
  - boutique-gateway
  http:
  - route:
    - destination:
        host: frontend
    timeout: 1s
    retries:
      attempts: 1
      perTryTimeout: 1s
      retryOn: gateway-error,connect-failure,refused-stream
