apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: server
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        - name: LOG_LEVEL
          value: "error"
        - name: NODE_ENV
          value: "staging"
        - name: DEBUG
          value: "false"
        - name: REDIS_TIMEOUT
          value: "1000"
        - name: CACHE_TTL
          value: "600"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi 