apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: server
        env:
        - name: ENABLE_PROFILER
          value: "0"
        - name: LOG_LEVEL
          value: "error"
        - name: NODE_ENV
          value: "staging"
        - name: DEBUG
          value: "false"
        - name: API_TIMEOUT
          value: "5000"
        - name: CACHE_TTL
          value: "600"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi 