apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: server
        env:
        - name: LOG_LEVEL
          value: "error"
        - name: NODE_ENV
          value: "staging"
        - name: DEBUG
          value: "false"
        - name: CACHE_TTL
          value: "600"
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 600m
            memory: 512Mi 