apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: server
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: ENABLE_PROFILER
          value: "0"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi 