apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: server
        env:
        - name: LOG_LEVEL
          value: "error"
        - name: ENABLE_PROFILER
          value: "0"
        - name: NODE_ENV
          value: "production"
        - name: DEBUG
          value: "false"
        - name: PAYMENT_TIMEOUT
          value: "5000"
        - name: CACHE_TTL
          value: "600"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
 